name: cicd

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "node"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create .env file
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "SLACK_URL=${{ secrets.SLACK_URL }}" >> .env

      - name: Build Docker Image
        run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/meal-plan:latest

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/meal-plan:latest

      - name: SSH remote and Run Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            sudo docker stop meal-plan
            sudo docker rm meal-plan
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/meal-plan:latest
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/meal-plan:latest
            sudo docker run --restart=unless-stopped -d -p 3001:3002 --name meal-plan ${{ secrets.DOCKERHUB_USERNAME }}/meal-plan:latest
            echo ">hello"
